# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-03 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='contacts',
        ),
        migrations.AddField(
            model_name='contacts',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='v1.Person'),
            preserve_default=False,
        ),
    ]
